#!/bin/sh
# Print the PKGBUILD of the AUR package xivly-bin for a release: the published
# .deb, unpacked. Its .SRCINFO is generated from it with `makepkg --printsrcinfo`.
# depends: the libraries the binary links (readelf -d), by the Arch package that
# ships them. Nothing else: Tauri's tray and xdotool features are not used.
# The license is the repository's LICENSE at the tag (the .deb has none); its
# sha256 is computed from this checkout, so run this from the release's tag.
# Usage: scripts/aur.sh <version> <.deb sha256> [pkgrel]
set -eu
VERSION=$1 SHA=$2 PKGREL=${3:-1}
LICENSE_SHA=$(sha256sum "$(dirname "$0")/../LICENSE" | cut -d' ' -f1)

cat <<PKGBUILD
# Maintainer: Julien Blanchon <julien@blanchon.cc>
# Generated by scripts/aur.sh in https://github.com/julien-blanchon/xivly (release workflow): change it there.

pkgname=xivly-bin
pkgver=$VERSION
pkgrel=$PKGREL
pkgdesc='Read, annotate and organize research papers, without distraction'
arch=('x86_64')
url='https://github.com/julien-blanchon/xivly'
license=('MIT')
depends=('cairo' 'dbus' 'gdk-pixbuf2' 'glib2' 'glibc' 'gtk3' 'hicolor-icon-theme' 'libgcc' 'libsoup3' 'webkit2gtk-4.1')
optdepends=('xdg-utils: open links and files in other apps')
provides=("xivly=\$pkgver")
conflicts=('xivly')
options=('!strip' '!debug')
source=("https://github.com/julien-blanchon/xivly/releases/download/v\$pkgver/Xivly_\${pkgver}_amd64.deb"
        "xivly-\$pkgver-LICENSE::https://raw.githubusercontent.com/julien-blanchon/xivly/v\$pkgver/LICENSE")
sha256sums=('$SHA'
            '$LICENSE_SHA')

package() {
  bsdtar -xf data.tar.* -C "\$pkgdir"
  # Tauri puts the 256 px icon in 256x256@2 (the folder of 512 px icons shown at 256): move it.
  local icons="\$pkgdir/usr/share/icons/hicolor"
  if [ -d "\$icons/256x256@2" ]; then
    mv "\$icons/256x256@2" "\$icons/256x256"
  fi
  install -Dm644 "xivly-\$pkgver-LICENSE" "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
}
PKGBUILD
